version: 2

models:
  - name: stg_shipments
    description: "Staging model: Cleans and standardizes raw shipment CDC data extracted from the PostgreSQL operational database."
    columns:
      - name: tracking_code
        description: "Global UUID for the shipment. Used as the true primary key."
        tests:
          - unique
          - not_null
      - name: shipment_id
        description: "The internal database ID (no longer guaranteed unique due to DB sequence resets)."
      - name: shipment_status
        description: "Current lifecycle state of the shipment. Simulates soft-deletes via the Cancelled status."
        tests:
          - accepted_values:
              arguments:   # <--- This is the required syntax for dbt 2.0+
                values: ['Pending', 'In Transit', 'Delivered', 'Cancelled', 'Delayed', 'Unknown'] 
      - name: hub_id
        description: "Foreign key to the hubs dimension table."
        tests:
          - not_null

  - name: int_weather_consensus
    description: "Intermediate model: Aggregates Tomorrow.io, OpenWeather, and Open-Meteo APIs using an hourly voting mechanism to determine the true weather condition per city."
    columns:
      - name: hub_city
        description: "The city where the weather consensus was calculated."
        tests:
          - not_null
      - name: weather_code
        description: "The finalized weather classification code after API voting."
        tests:
          - not_null

  - name: fact_shipment_weather
    description: "Gold layer Data Mart: Joins operational shipment data with the intermediate weather consensus to analyze weather impact on delivery times."
    columns:
      - name: tracking_code
        description: "Global UUID inherited from shipments. True unique identifier."
        tests:
          - unique
          - not_null
      - name: shipment_id
        description: "Internal database ID inherited from shipments."